# Copyright (c) 2023-2024, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

header = """/*
 * Copyright (c) 2023-2024, NVIDIA CORPORATION.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * NOTE: this file is generated by search_single_cta_00_generate.py
 *
 * Make changes there and run in this directory:
 *
 * > python search_single_cta_00_generate.py
 *
 */

#include "sample_filter_utils.cuh"
#include "search_single_cta_inst.cuh"

#define COMMA ,

namespace cuvs::neighbors::my_anns_v1::detail::single_cta_search {
"""

trailer = """
}  // namespace cuvs::neighbors::my_anns_v1::detail::single_cta_search
"""

# block = [(64, 16), (128, 8), (256, 4), (512, 2), (1024, 1)]
# itopk_candidates = [64, 128, 256]
# itopk_size = [64, 128, 256, 512]
# mxelem = [64, 128, 256]

# rblock = [(256, 4), (512, 2), (1024, 1)]
# rcandidates = [32]
# rsize = [256, 512]

search_types = dict(
    float_uint32=("float", "uint32_t", "float"),  # data_t, idx_t, distance_t
    half_uint32=("half", "uint32_t", "float"),
    int8_uint32=("int8_t", "uint32_t", "float"),
    uint8_uint32=("uint8_t", "uint32_t", "float"),
)

# knn
for type_path, (data_t, idx_t, distance_t) in search_types.items():
    for entry_points_policy, entry_points_path in (
            (f"ComputeRandomEntryPoints<{idx_t}>", "compute_random"),
            (f"MemcpyEntryPoints<{idx_t} COMMA {distance_t}>", "memcpy")):
        for visited_table, visited_table_path in (
                (f"visited_table::SingleMemHashtable<{idx_t}>", "single_mem_hash"),
                (f"visited_table::Cache<{idx_t}>", "cache"),
                ):
            path = f"search_single_cta_{type_path}_{entry_points_path}_{visited_table_path}.cu"
            with open(path, "w") as f:
                f.write(header)
                for sample_filter in ("cuvs::neighbors::filtering::none_sample_filter", "my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>"):
                            f.write(
                                    f"instantiate_kernel_selection(\n  {data_t}, {idx_t}, {distance_t}, {sample_filter}, {entry_points_policy}, {visited_table});\n"
                            )

                f.write(trailer)
                # For pasting into CMakeLists.txt
                print(f"src/neighbors/detail/my_anns_v1/{path}")
