/*
 * Copyright (c) 2023-2024, NVIDIA CORPORATION.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * NOTE: this file is generated by search_single_cta_00_generate.py
 *
 * Make changes there and run in this directory:
 *
 * > python search_single_cta_00_generate.py
 *
 */

#pragma once

#include "compute_distance-ext.cuh"

#include "sample_filter_utils.cuh"
#include <cuvs/neighbors/my_anns_v1.hpp>
#include <cuvs/neighbors/my_anns_v1_metrics.cuh>
#include "visited_table.cuh"
#include "entry_points_policy.cuh"
#define COMMA ,

namespace cuvs::neighbors::my_anns_v1::detail::single_cta_search {

template <typename DataT,
          typename IndexT,
          typename DistanceT,
          typename SampleFilterT,
          typename EntryPointsPolicy,
          class VisitedTable>
void select_and_run(const dataset_descriptor_host<DataT, IndexT, DistanceT>& dataset_desc,
                    raft::device_matrix_view<const IndexT, int64_t, raft::row_major> graph,
                    IndexT* topk_indices_ptr,       // [num_queries, topk]
                    DistanceT* topk_distances_ptr,  // [num_queries, topk]
                    const DataT* queries_ptr,       // [num_queries, dataset_dim]
                    uint32_t num_queries,
                    uint32_t* num_executed_iterations,  // [num_queries,]
                    const search_params& ps,
                    uint32_t topk,
                    uint32_t num_itopk_candidates,
                    uint32_t block_size,  //
                    uint32_t smem_size,
                    SampleFilterT sample_filter,
                    const EntryPointsPolicy& entry_points_policy,
                    VisitedTable& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
                    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
                    cudaStream_t stream);
    
extern template void select_and_run<float, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, ComputeRandomEntryPoints<uint32_t>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<float, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const float* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<float, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, ComputeRandomEntryPoints<uint32_t>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<float, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const float* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<float, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, ComputeRandomEntryPoints<uint32_t>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<float, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const float* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<float, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, ComputeRandomEntryPoints<uint32_t>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<float, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const float* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<float, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, ComputeRandomEntryPoints<uint32_t>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<float, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const float* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<float, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, ComputeRandomEntryPoints<uint32_t>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<float, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const float* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<float, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<float, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const float* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<float, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<float, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const float* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<float, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<float, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const float* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<float, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<float, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const float* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<float, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<float, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const float* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<float, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<float, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const float* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<half, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, ComputeRandomEntryPoints<uint32_t>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<half, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const half* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<half, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, ComputeRandomEntryPoints<uint32_t>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<half, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const half* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<half, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, ComputeRandomEntryPoints<uint32_t>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<half, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const half* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<half, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, ComputeRandomEntryPoints<uint32_t>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<half, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const half* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<half, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, ComputeRandomEntryPoints<uint32_t>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<half, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const half* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<half, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, ComputeRandomEntryPoints<uint32_t>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<half, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const half* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<half, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<half, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const half* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<half, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<half, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const half* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<half, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<half, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const half* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<half, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<half, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const half* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<half, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<half, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const half* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<half, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<half, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const half* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<int8_t, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, ComputeRandomEntryPoints<uint32_t>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<int8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const int8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<int8_t, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, ComputeRandomEntryPoints<uint32_t>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<int8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const int8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<int8_t, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, ComputeRandomEntryPoints<uint32_t>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<int8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const int8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<int8_t, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, ComputeRandomEntryPoints<uint32_t>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<int8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const int8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<int8_t, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, ComputeRandomEntryPoints<uint32_t>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<int8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const int8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<int8_t, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, ComputeRandomEntryPoints<uint32_t>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<int8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const int8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<int8_t, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<int8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const int8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<int8_t, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<int8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const int8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<int8_t, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<int8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const int8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<int8_t, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<int8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const int8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<int8_t, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<int8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const int8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<int8_t, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<int8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const int8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<uint8_t, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, ComputeRandomEntryPoints<uint32_t>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<uint8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const uint8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<uint8_t, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, ComputeRandomEntryPoints<uint32_t>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<uint8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const uint8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<uint8_t, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, ComputeRandomEntryPoints<uint32_t>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<uint8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const uint8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<uint8_t, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, ComputeRandomEntryPoints<uint32_t>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<uint8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const uint8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<uint8_t, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, ComputeRandomEntryPoints<uint32_t>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<uint8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const uint8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<uint8_t, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, ComputeRandomEntryPoints<uint32_t>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<uint8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const uint8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const ComputeRandomEntryPoints<uint32_t>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<uint8_t, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<uint8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const uint8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<uint8_t, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::SingleMemHashtable<uint32_t>>(
    const dataset_descriptor_host<uint8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const uint8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::SingleMemHashtable<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<uint8_t, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<uint8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const uint8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<uint8_t, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::Cache<uint32_t>>(
    const dataset_descriptor_host<uint8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const uint8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::Cache<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<uint8_t, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<uint8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const uint8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    cuvs::neighbors::filtering::none_sample_filter sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
extern template void select_and_run<uint8_t, uint32_t, float, my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>, MemcpyEntryPoints<uint32_t COMMA float>, visited_table::AlwaysUnvisited<uint32_t>>(
    const dataset_descriptor_host<uint8_t, uint32_t, float>& dataset_desc,
    raft::device_matrix_view<const uint32_t,int64_t,raft::row_major> graph,
    uint32_t* topk_indices_ptr,
    float* topk_distances_ptr,
    const uint8_t* queries_ptr,
    uint32_t num_queries,
    uint32_t* num_executed_iterations,
    const search_params& ps,
    uint32_t topk,
    uint32_t num_itopk_candidates,
    uint32_t block_size,
    uint32_t smem_size,
    my_anns_v1SampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>> sample_filter,
    const MemcpyEntryPoints<uint32_t COMMA float>& entry_points_policy,
    visited_table::AlwaysUnvisited<uint32_t>& visited_table,
#ifdef _GRAPH_QUALITY_ANALYSIS
    MyAnnsV1Metrics* my_anns_v1_metrics,
#endif
    cudaStream_t stream);

    
}  // namespace cuvs::neighbors::my_anns_v1::detail::single_cta_search
    