name: ganns_nsw
constraints:
  build: cuvs_bench.config.algos.constraints.ganns_build
  search: cuvs_bench.config.algos.constraints.ganns_search
groups:
  base:
    build:
      hierarchical: [False]
      num_of_candidates_build: [16, 32, 64]
      num_of_initial_neighbors: [64]
    search:
      num_of_candidates_search: [16, 32, 64]

