name: song
constraints:
  build: cuvs_bench.config.algos.constraints.song_build
  search: cuvs_bench.config.algos.constraints.song_search
groups:
  base:
    build:
      num_threads: [32]
      degree: [15]
    search:
      # finish_cnt: [1, 5, 10, 100, 400]
      finish_cnt: [400, 600, 800, 1000, 1200, 1600, 2000, 3000, 5000]
      pq_size: [20, 50, 100, 200, 400, 800, 1600, 3200]
  ncu:
    build:
      num_threads: [32]
      degree: [15]
    search:
      finish_cnt: [2000]
      pq_size: [800]
