name: song
constraints:
  build: cuvs_bench.config.algos.constraints.song_build
  search: cuvs_bench.config.algos.constraints.song_search
groups:
  base:
    build:
      num_threads: [32]
      degree: [15]
    search:
      # finish_cnt: [1, 5, 10, 100, 400]
      finish_cnt: [400, 600, 800, 1000, 1200, 1400, 1600]
      pq_size: [20, 30, 40, 60, 80, 100, 150, 200]
